# Auto-labeling configuration for PRs

# Runtime-related changes
'area: runtime':
  - 'src/runtime/**/*'
  - 'tests_integ/runtime.test.ts'

# Browser tool changes
'area: browser':
  - 'src/tools/browser/**/*'
  - 'tests_integ/browser.test.ts'

# Code interpreter changes
'area: code-interpreter':
  - 'src/tools/code-interpreter/**/*'
  - 'tests_integ/code-interpreter.test.ts'

# Documentation changes
'type: docs':
  - '**/*.md'
  - 'docs/**/*'

# Test changes
'type: test':
  - '**/*.test.ts'
  - 'tests_integ/**/*'

# Build/CI changes
'type: build':
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - 'vite.config.ts'
  - 'vitest.config.ts'
  - '.github/**/*'

# Example changes
'type: examples':
  - 'examples/**/*'

# Dependencies
'dependencies':
  - 'package.json'
  - 'package-lock.json'
